channels:
- conda-forge

dependencies:
- python=3.14
- jupyter-book>=2
- mystmd
- ghp-import # maybe github pages...?
- pyyaml

- pip

# - pip:
#   - -r requirements.txt # do we need anything that's not on conda-forge?
